In [3]:
class python:
    def func():
        print("Hello world")
    
    func()        

Hello world


In [2]:
class notebook:
    pages=200
    name="history"
    label="standard book"

In [3]:
example_instance=notebook()
print(example_instance.pages)
print(example_instance.name)
print(example_instance.label)

200
history
standard book


In [4]:
#numpy-- numerical python
#importing a library
import numpy as np

In [5]:
#we create an array
a=np.array([[3,6,5,8],[12,13,15]])
print(a)
print(type(a))
print(a[0])

[list([3, 6, 5, 8]) list([12, 13, 15])]
<class 'numpy.ndarray'>
[3, 6, 5, 8]


In [6]:
a.dtype

dtype('O')

In [7]:
a[0]

[3, 6, 5, 8]

In [8]:
b=np.array([[5,6,9],[10,13,16]])
print(b)

[[ 5  6  9]
 [10 13 16]]


In [9]:
print(b[1])

[10 13 16]


In [10]:
b.shape

(2, 3)

In [11]:
#dimension
b.ndim

2

In [12]:
b=np.array([[5,6],[10,13,16]])
print(b)
b.shape
b.ndim

[list([5, 6]) list([10, 13, 16])]


1

In [13]:
#we want to create 2 dimension array everytime it will come as (1,)(3,)(7,)
a=np.array([30])
a.shape

(1,)

In [14]:
a.shape

(1,)

In [15]:
a.ndim

1

In [16]:
# 2 dimension
d=np.array([[4,5],[9,3]])
print(d.shape)
print(d.ndim)

(2, 2)
2


In [17]:
#3 dimension
arr=np.array([[[5,6,12],[59,7,98]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[ 5  6 12]
  [59  7 98]]]
(1, 2, 3)
3


In [18]:
A = np.array([[[[ 0, 1], [ 2, 3], [ 4, 5], [ 6, 7]]]])
A

array([[[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]])

In [19]:
A.shape
#A.ndim

(1, 1, 4, 2)

In [20]:
#create a array having dimension and 3 and shape (3,2,1)
a=np.array([[[10],[20]],[[30],[40]],[[50],[60]]])
print(a)
print(a.shape)
print(a.ndim)

[[[10]
  [20]]

 [[30]
  [40]]

 [[50]
  [60]]]
(3, 2, 1)
3


In [21]:
c=np.array([2,3])
print(c)

[2 3]


In [22]:
print(c.size)
print(c.shape)
print(c.ndim)

2
(2,)
1


In [23]:
#2d array
r=np.array([[4,2],[5,9]])
print(r)
print(r.shape)
print(r.ndim)

[[4 2]
 [5 9]]
(2, 2)
2


In [24]:
#3d array
c=np.array([[[4],[5]]])
print(c)
print(c.shape)
print(c.ndim)

[[[4]
  [5]]]
(1, 2, 1)
3


In [25]:
#create a 4d which has shape (2,3,2,3)
a=np.array([[[[1,4,6],[3,8,9]],[[1,4,6],[3,8,9]],[[1,4,6],[3,8,9]]],[[[1,4,6],[3,8,9]],[[1,4,6],[3,8,9]],[[1,4,6],[3,8,9]]]])
print(a)
print(a.shape)
print(a.ndim)

[[[[1 4 6]
   [3 8 9]]

  [[1 4 6]
   [3 8 9]]

  [[1 4 6]
   [3 8 9]]]


 [[[1 4 6]
   [3 8 9]]

  [[1 4 6]
   [3 8 9]]

  [[1 4 6]
   [3 8 9]]]]
(2, 3, 2, 3)
4


In [26]:
# 4D array
arr=np.array([[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]],[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[[1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]]]


 [[[1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]]]]
(2, 3, 2, 3)
4


In [27]:
num=np.array([[5,6],[4,9]])
print(num.shape,num.ndim)
print(num[1,1])
print(num)
num[0]

(2, 2) 2
9
[[5 6]
 [4 9]]


array([5, 6])

In [28]:
# we are accessing the rows
print(num[0,0])


5


In [29]:
# we are accessing the columns
print(num[:,1])

[6 9]


In [30]:
num[:,0]

array([5, 4])

In [31]:
print(num[0],num[1])


[5 6] [4 9]


In [32]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
#accessing row
a[:1]

array([[1, 2, 3]])

In [34]:
#accessing column
a[:,1]

array([2, 5, 8])

In [35]:
a[:,0]

array([1, 4, 7])

In [36]:
# numpy array is mutable
num[1,1]=10
print(num)

[[ 5  6]
 [ 4 10]]


In [37]:
num[1,1]

10

In [38]:
grid=np.array([1,2,3,4])
print(grid[0],grid[1],grid[2])


1 2 3


In [39]:
f=np.array([[4,2,1],[6,7,8]])
print(f[0,0],f[0,1],f[1,0])

4 2 6


In [40]:
#numpy also provides many functions to create array
#zeros() function
r=np.zeros([2,2,2])
print(r)
print(r.ndim)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
3


In [41]:
#ones() function
e=np.ones([2,3,4])
print(e)
print(type(e))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<class 'numpy.ndarray'>


In [42]:
#full() - it print the number that you provide
q=np.full([2,3],9)
print(q)

[[9 9 9]
 [9 9 9]]


In [43]:
#identity matrix
# eye() -used for identity matrix
w=np.eye(3)
print(w)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
x=np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [45]:
#random.random() function
t=np.random.random([3,4])
t

array([[0.62602901, 0.28899367, 0.29629596, 0.12993422],
       [0.49752262, 0.44243035, 0.35374464, 0.50616785],
       [0.74092486, 0.37608131, 0.67705161, 0.96243089]])

In [46]:
#slicing values
g=np.array([[2,3,4,5],[5,6,7,8],[9,10,11,13]])
print(g)
f=g[:2,1:3]
print(f)

[[ 2  3  4  5]
 [ 5  6  7  8]
 [ 9 10 11 13]]
[[3 4]
 [6 7]]


In [47]:
# interelated
print(g[0,1])
f[0,0]=45
print(g)
f

3
[[ 2 45  4  5]
 [ 5  6  7  8]
 [ 9 10 11 13]]


array([[45,  4],
       [ 6,  7]])

In [48]:
g=np.array([[2,3,4,5],[5,6,7,8],[9,10,11,13]])
print(g)
print(g[1:3,1:4])
row1=g[1,:]
row2=g[1:2,:]
print(row1)
print(row2)
print(g.shape)

[[ 2  3  4  5]
 [ 5  6  7  8]
 [ 9 10 11 13]]
[[ 6  7  8]
 [10 11 13]]
[5 6 7 8]
[[5 6 7 8]]
(3, 4)


In [49]:
g.shape

(3, 4)

In [50]:
col1=g[:,0:1]
col2=g[:]
print(col1)

[[2]
 [5]
 [9]]


In [51]:
col1=g[:,3]
print(col1)

[ 5  8 13]


In [52]:
#integer array indexing
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])  #[0,0] [1,1] [2,0]
print(a[0,0],a[1,1],a[2,0])

[1 4 5]
1 4 5


In [53]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
#print(a)
b=np.array([0,2,0,1]) #consider row in order
print(a[np.arange(4),b])

[ 1  6  7 11]


In [54]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:
b

array([0, 2, 0, 1])

In [56]:
#04-OCT-2021
# arange function
import numpy as np
t=np.array([[3,7,5],[4,10,8],[2,13,1],[17,6,9]])
print(t.shape)
print(t)

(4, 3)
[[ 3  7  5]
 [ 4 10  8]
 [ 2 13  1]
 [17  6  9]]


In [57]:
u=np.array([0,2,0,2])
print(t[np.arange(4),u])

[3 8 2 9]


In [58]:
t[np.arange(4),u] += 10
print(t)

[[13  7  5]
 [ 4 10 18]
 [12 13  1]
 [17  6 19]]


In [59]:
u=np.array([0,2,0])
print(t[np.arange(3)])

[[13  7  5]
 [ 4 10 18]
 [12 13  1]]


In [60]:
t=np.array([[3,7,5,21],[4,10,8,20],[2,13,1,16],[17,6,9,19]])
print(t.shape)
print(t)

(4, 4)
[[ 3  7  5 21]
 [ 4 10  8 20]
 [ 2 13  1 16]
 [17  6  9 19]]


In [61]:
u=np.array([0,2,0,2])  #(0,0),(1,2),(2,0),(3,2)
print(t[np.arange(4),u])

[3 8 2 9]


In [62]:
u=np.array([[0,0],[1,1],[2,2],[3,3]])
print(t)
print(t[np.arange(1),u])

[[ 3  7  5 21]
 [ 4 10  8 20]
 [ 2 13  1 16]
 [17  6  9 19]]
[[ 3  3]
 [ 7  7]
 [ 5  5]
 [21 21]]


In [63]:
#diff between range and arange

In [64]:
#boolean array indexing
f=np.array([[3,2],[5,8],[9,1]])
less_than_2=(f<2)
print(less_than_2)
print(f)

[[False False]
 [False False]
 [False  True]]
[[3 2]
 [5 8]
 [9 1]]


In [65]:
f=np.array([[3,2],[5,8],[9,1]])
less_than_2=(f>2)
print(less_than_2)
print(f.dtype)

[[ True False]
 [ True  True]
 [ True False]]
int32


In [66]:
print(f[less_than_2])
print(f[f>2])

[3 5 8 9]
[3 5 8 9]


In [67]:
#dtype - find datatype of the elements that are stored in array
c=np.array([4,8],dtype='int64')   #by default -int 32 from range int8 to int64
print(c.dtype)

int64


In [68]:
d=np.array(['hello'])
print(d.dtype)

<U5


In [69]:
a=np.array([5j],dtype='complex64')#by default-complex128 range from complex64 to complex128
a.dtype

dtype('complex64')

In [70]:
g=np.array([9.0],dtype='float64')#by default-float64 range from float16 to float64
print(g.dtype)

float64


In [71]:
#mathematical functions
x=np.array([10.5,14.5])
print(x.dtype)
y=np.array([23,21])
print(y.dtype)
z=(x+y)


float64
int32


In [72]:
print(z.dtype)

float64


In [73]:
x=np.array([10,14])
print(x.dtype)
y=np.array([23,21])
print(y.dtype)
z=(x+y)


int32
int32


In [74]:
print(z)

[33 35]


In [75]:
print(np.add(x,y))

[33 35]


In [76]:
print(np.subtract(x,y))
print(x-y)

[-13  -7]
[-13  -7]


In [77]:
print(np.multiply(x,y))
print(x*y)

[230 294]
[230 294]


In [78]:
print(np.divide(x,y))
print(x/y)

[0.43478261 0.66666667]
[0.43478261 0.66666667]


In [79]:
print(np.sqrt([x,y]))

[[3.16227766 3.74165739]
 [4.79583152 4.58257569]]


In [80]:
np.sqrt(y)

array([4.79583152, 4.58257569])

In [81]:
print(np.square(x))

[100 196]


In [82]:
print(np.square(y))

[529 441]


In [83]:
#05-OCT-2021
#dot function
a=np.array([[[10,11],[25,26]]])
b=np.array([[8,9],[3,4]])
c=np.array([33,44])
d=np.array([66,77])
print(c.dot(d))     #33* 66+44*77
print(np.dot(c,d))
print(a.dot(b))
print(np.dot(a,b))

5566
5566
[[[113 134]
  [278 329]]]
[[[113 134]
  [278 329]]]


In [84]:

print(np.dot(a,c))  # 10*33+11*44=814 and 25*33+26*44=1969

[[ 814 1969]]


In [86]:
# sum
a=np.array([[[10,11],[25,26],[2,4]]])
print(a.sum())
print(np.sum(a,axis=0)) #compute sum of each col
print(np.sum(a,axis=1)) #compute sum of each rows


78
[[10 11]
 [25 26]
 [ 2  4]]
[[37 41]]


In [90]:
a=np.array([[[10,11,1],[25,26,2],[2,4,5]]])
print(np.sum(a,axis=2))
print(a.ndim)

[[22 53 11]]
3


In [91]:
print(a)

[[[10 11  1]
  [25 26  2]
  [ 2  4  5]]]


In [92]:
print(np.sum(a,axis=0))

[[10 11  1]
 [25 26  2]
 [ 2  4  5]]


In [100]:
# manipulating the data in an array
# Transposing (T)
t=np.array([[4,7],[9,10]])
print(t)
print(t.T)

[[ 4  7]
 [ 9 10]]
[[ 4  9]
 [ 7 10]]


In [101]:
a=np.array([1,2])
print(a.T)

[1 2]


In [103]:
b=np.array([1,2,3])   
print(b)
print(b.T)

[1 2 3]
[1 2 3]


In [106]:
a=np.array([3,6,8])
print(a)
print(a.T)

[3 6 8]
[3 6 8]


In [122]:
# BROADCASTING
a=np.array([[12,13],[4,5],[8,9],[14,15]])
b=np.array([1,0])
c=np.empty_like(a)


In [123]:
for i in c:
    c=a+b

In [124]:
print(c)

[[13 13]
 [ 5  5]
 [ 9  9]
 [15 15]]


In [137]:
a=np.array([[12,13,3],[17,4,5],[14,8,9],[16,14,15]])
b=np.array([1,0,1])
c=np.empty_like(a)
print(a)

[[12 13  3]
 [17  4  5]
 [14  8  9]
 [16 14 15]]


In [142]:
for i in c:
    c=a+b

In [143]:
print(c)  # (12+1 13+0 3+1) (17+1 4+0 5+1) (14+1 8+0 9+1) (16+1 14+0 15+1)

[[13 13  4]
 [18  4  6]
 [15  8 10]
 [17 14 16]]


In [146]:
for i in range(4):
    c[i,:]=a[i,:]+b   

In [147]:
print(c)

[[13 13  4]
 [18  4  6]
 [15  8 10]
 [17 14 16]]


In [160]:
# tile() function
a=np.array([[12,13,3],[17,4,5],[14,8,9],[16,14,15]])
b=np.array([1,0,1])
c=np.tile(b,(4,1))
print(c)
d=a+c

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [161]:
print(d)

[[13 13  4]
 [18  4  6]
 [15  8 10]
 [17 14 16]]


In [177]:
# reshape() function
s=np.array([10,4,5])
t=np.array([8,2])
print(np.reshape(s,(3,1))*t)

[[80 20]
 [32  8]
 [40 10]]


In [178]:
s=np.array([10,4])
t=np.array([8,2])
print(np.reshape(s,(2,1))*t)

[[80 20]
 [32  8]]


In [183]:
s=np.array([10,4])
t=np.array([8,2,3])
c=(np.reshape(s,(2,1))*t)

In [184]:
print(c)

[[80 20 30]
 [32  8 12]]


In [194]:
s=np.array([10,4,6])
t=np.array([8,2])
c=(np.reshape(s,(3,1))*t)
print(c)

[[80 20]
 [32  8]
 [48 12]]


In [195]:
x=np.array([[3,9,2],[7,5,10]])
print(x+s)

[[13 13  8]
 [17  9 16]]


In [197]:
print((x.T+t))

[[11  9]
 [17  7]
 [10 12]]


In [198]:
print((x.T+t).T)

[[11 17 10]
 [ 9  7 12]]


In [200]:
print(x+np.reshape(t,(2,1)))

[[11 17 10]
 [ 9  7 12]]


In [1]:
# 06-OCT-2021
#
import numpy as np